# related discussion https://stackoverflow.com/a/69009486
# kind docs regarding this bit https://kind.sigs.k8s.io/docs/user/configuration#nodeport-with-port-mappings

kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  # containerPort has to be the same port that is configured in values-ingress-nginx
  # this port is exposed from the cluster container
  - containerPort: 30080
    # host OS port which is called from the browser e.g. when UI is opened
    hostPort: 40110
    # listens to all interfaces
    listenAddress: "0.0.0.0"

    # open postgres db to the outside world that you can connect to the db from the outside of your local-env cluster
  - containerPort: 30100 
    hostPort: 30100        
    listenAddress: "0.0.0.0"