name: E2E Tests Execution Against Local Env

on:
  push:
    branches:
      - feature/*

jobs:
  run-e2e-against-local-env:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout Local Env
      uses: actions/checkout@v4

    - name: Deploy Local Env to Kind k8s
      uses: devcontainers/ci@v0.3
      with:
        runCmd: |
          kind create cluster --name pelican --config kind-local-config.yaml --kubeconfig ./.pelican-cluster-kubeconfig
          helmfile cache cleanup && helmfile --environment local --namespace local -f deploy/helmfile.yaml apply
        # we don't need to push docker image that was built using our Dev Container
        push: never

    # PLAYWRIGHT UI TESTS

    - name: Checkout Pelican UI
      uses: actions/checkout@v4
      with:
        repository: TourmalineCore/pelican-ui
        # we need to specify this path otherwise it will create this folder pelican-local-env/pelican-local-env
        # and that will lead to permissions error at the next CMS repo checkout when it tries to remove no longer needed folder
        # this path that matches the repo name isolates UI src folder from CMS one
        path: pelican-ui

    - name: Playwright Run Against UI
      uses: devcontainers/ci@v0.3
      with:
        subFolder: pelican-ui
        # we expect that UI repo as well as CMS one contains the needed Dev Container configuration
        # that allows us to get rid of caching and installation of deps here and rely of docker images more
        configFile: ./pelican-ui/.devcontainer/e2e-tests-in-pr/devcontainer.json
        runCmd: |
          npx playwright test --reporter=html --config=playwright.e2e.config.ts
        # we don't need to push docker image that was built using our Dev Container
        push: never
        # we forward CI env var value from GitHub to Dev Container
        # without it CI is not defined
        env: |
          FRONTEND_URL=http://localhost:40110 
          API_URL=http://localhost:40110/cms/api
          CI

    - name: Upload HTML report
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: html-report--attempt-${{ github.run_attempt }}
        path: playwright-report
        retention-days: 7

    # PLAYWRIGHT CMS TESTS

    - name: Checkout Pelican CMS
      uses: actions/checkout@v4
      with:
        repository: TourmalineCore/pelican-cms
        path: pelican-cms

    - name: Playwright Run Against CMS
      uses: devcontainers/ci@v0.3
      with:
        subFolder: pelican-cms
        configFile: ./pelican-cms/.devcontainer/e2e-tests-in-pr/devcontainer.json
        runCmd: |
          npx playwright test --reporter=html
        push: never
        env: |
          FRONTEND_URL=http://localhost:40110
          SERVER_URL=http://localhost:40110/cms

    - name: Upload HTML report
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: html-report--attempt-${{ github.run_attempt }}
        path: playwright-report
        retention-days: 7
